name: Release Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v4
      with:
        flutter-version: '3.13.0' 

    - name: Install dependencies
      run: flutter pub get

    - name: Build Universal APK
      run: flutter build apk --release

    - name: Build Split ABI APKs
      run: flutter build apk --split-per-abi --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
       path: build/app/outputs/flutter-apk/*.apk
